Removing Data dir as it isn't used and providing functionality been removed.
See: http://docs.puppetlabs.com/puppet/3/reference/experiments_binder.html

Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Conflicting binding for name: 'package_name' in layer:
'modules', from: 'module-hiera:/haproxy', and 'module-hiera:/collectd'
on node FQDN.